# Change these first
owner: DokaGG # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Helalk Main
    url: https://www.helalk.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.helalk.com # Custom domain CNAME
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/DokaGG/tools/refs/heads/main/assets/img/2024%20png.png
  name: Status
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: https://www.helalk.com/p/contact-us.html
delay: 2000 # 2 seconds
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
